language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
sudo: false
before_script:
- npm run init
script:
- npm run testNode
env:
  global:
  - secure: X5NX0AXb+mMSzhFjvwwB/qwmH3bgiDn61XZIQjzNyM8rMvapfPOnWmYvODhwyE5jOcic7kD37uc0LjF/s8u+ZLp1UYyLNxeumIi+t6Z4fjpVGDD9MGFAHsPH4T+T3i5jFR4WMB/V8fFY4Ok/rxmJ0wbf0eOmIYKfCC1xA8lLBIQ=
  - secure: aHvp2CDHPAHbv2QG/CBfDQBWbE2OkBH/TFJDoi2fLl0a9CDTxvxjUXPOZImnNoeLNIlN7KgOTPCQjVuvs9N5CKvJC0h3YQQ4UaAG5wQky3dXNxCUViGTn7ZHeBr9fJBzXJIwBo9ynrcAAJAWOI3ugdPewRUw92VJFbbAntQwAw0=
